/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab04;

import EmployeeModel.Employee;
import EmployeeModel.EmployeeDirectory;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Akash
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    JPanel BottomPanel;
    EmployeeDirectory Employees;
    
    public CreatePanel(JPanel BottomPanel, EmployeeDirectory Employees) {
        initComponents();
        this.BottomPanel = BottomPanel;
        this.Employees = Employees;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Namelabel = new javax.swing.JLabel();
        IDlabel = new javax.swing.JLabel();
        Agelabel = new javax.swing.JLabel();
        Genderlabel = new javax.swing.JLabel();
        Startdatelabel = new javax.swing.JLabel();
        Levellabel = new javax.swing.JLabel();
        Contactlabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        Photolabel = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Uploadbutton = new javax.swing.JButton();
        Namefield = new javax.swing.JTextField();
        IDfield = new javax.swing.JTextField();
        Agefield = new javax.swing.JTextField();
        Genderfield = new javax.swing.JTextField();
        StartdateChooser = new com.toedter.calendar.JDateChooser();
        Levelfield = new javax.swing.JTextField();
        Phonefield = new javax.swing.JTextField();
        Emailfield = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Kefa", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Employee Details");

        Namelabel.setText("Name");

        IDlabel.setText("Employee ID");

        Agelabel.setText("Age");

        Genderlabel.setText("Gender");

        Startdatelabel.setText("Start Date");

        Levellabel.setText("Level");

        Contactlabel.setText("Contact Info :-");

        phonelabel.setText("Phone Number");

        Emaillabel.setText("Email Address");

        Photolabel.setText("Photo");

        Save.setBackground(new java.awt.Color(0, 153, 51));
        Save.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Uploadbutton.setText("Upload");
        Uploadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contactlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Photolabel)
                                .addGap(249, 249, 249)
                                .addComponent(Uploadbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Namelabel)
                                    .addComponent(IDlabel)
                                    .addComponent(Agelabel)
                                    .addComponent(Genderlabel)
                                    .addComponent(Startdatelabel)
                                    .addComponent(Levellabel))
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Namefield)
                                    .addComponent(IDfield)
                                    .addComponent(Agefield)
                                    .addComponent(Genderfield)
                                    .addComponent(StartdateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Levelfield)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonelabel)
                            .addComponent(Emaillabel))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Phonefield)
                            .addComponent(Emailfield))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Namelabel)
                                    .addComponent(Namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDlabel)
                                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Agelabel)
                                    .addComponent(Agefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Genderlabel)
                                    .addComponent(Genderfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Startdatelabel))
                            .addComponent(StartdateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Levellabel)
                            .addComponent(Levelfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Contactlabel)
                        .addGap(18, 18, 18)
                        .addComponent(phonelabel))
                    .addComponent(Phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emaillabel)
                    .addComponent(Emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Photolabel)
                    .addComponent(Uploadbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        Employee newEmployee = new Employee();
        try {
        //Employee newEmployee = new Employee();
        newEmployee.setName(Namefield.getText());
        newEmployee.setEmployeeID(IDfield.getText());
        newEmployee.setAge(Agefield.getText());
        newEmployee.setGender(Genderfield.getText());
        newEmployee.setStartDate(StartdateChooser.getDate());
        newEmployee.setLevel(Levelfield.getText());
        newEmployee.setPhoneNumber(Phonefield.getText());
        newEmployee.setEmailAddress(Emailfield.getText());
        }
        catch(Exception ex) {
         JOptionPane.showMessageDialog(this, "Please Enter Details", "Error", HEIGHT);
     }
        {
        Employees.addEmployee(newEmployee);
        System.out.println(Employees);
        JOptionPane.showMessageDialog(this, "Employee Details Saved Successfully", "Success", HEIGHT);
    }
        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void UploadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadbuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                Image edited_image = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
                if (edited_image != null) {
                    Photolabel.setText(file.getSelectedFile().getAbsolutePath());
                    
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please upload image correctly correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_UploadbuttonActionPerformed
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agefield;
    private javax.swing.JLabel Agelabel;
    private javax.swing.JLabel Contactlabel;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JTextField Genderfield;
    private javax.swing.JLabel Genderlabel;
    private javax.swing.JTextField IDfield;
    private javax.swing.JLabel IDlabel;
    private javax.swing.JTextField Levelfield;
    private javax.swing.JLabel Levellabel;
    private javax.swing.JTextField Namefield;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JTextField Phonefield;
    private javax.swing.JLabel Photolabel;
    private javax.swing.JButton Save;
    private com.toedter.calendar.JDateChooser StartdateChooser;
    private javax.swing.JLabel Startdatelabel;
    private javax.swing.JButton Uploadbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel phonelabel;
    // End of variables declaration//GEN-END:variables
}
