/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab04;

import EmployeeModel.Employee;
import EmployeeModel.EmployeeDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    JPanel BottomPanel;
    EmployeeDirectory Employees;
    public ViewPanel(JPanel BottomPanel, EmployeeDirectory Employees) {
        initComponents();
        this.BottomPanel = BottomPanel;
        this.Employees = Employees;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titlelabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        Deletebutton = new javax.swing.JButton();
        Viewbutton = new javax.swing.JButton();
        Namelabel = new javax.swing.JLabel();
        IDlabel = new javax.swing.JLabel();
        Agelabel = new javax.swing.JLabel();
        Genderlabel = new javax.swing.JLabel();
        Startdatelabel = new javax.swing.JLabel();
        Levellabel = new javax.swing.JLabel();
        Contactlabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        Namefield = new javax.swing.JTextField();
        IDfield = new javax.swing.JTextField();
        Agefield = new javax.swing.JTextField();
        Genderfield = new javax.swing.JTextField();
        StartdateChooser = new com.toedter.calendar.JDateChooser();
        Levelfield = new javax.swing.JTextField();
        Phonefield = new javax.swing.JTextField();
        Emailfield = new javax.swing.JTextField();
        Updatebutton = new javax.swing.JButton();

        Titlelabel.setFont(new java.awt.Font("Mshtakan", 1, 24)); // NOI18N
        Titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlelabel.setText("Employee Details");

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Phone Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmployeeTable);
        if (EmployeeTable.getColumnModel().getColumnCount() > 0) {
            EmployeeTable.getColumnModel().getColumn(1).setResizable(false);
            EmployeeTable.getColumnModel().getColumn(4).setResizable(false);
        }

        Deletebutton.setText("DELETE");
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });

        Viewbutton.setText("VIEW");
        Viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbuttonActionPerformed(evt);
            }
        });

        Namelabel.setText("Name");

        IDlabel.setText("Employee ID");

        Agelabel.setText("Age");

        Genderlabel.setText("Gender");

        Startdatelabel.setText("Start Date");

        Levellabel.setText("Level");

        Contactlabel.setText("Contact Info :-");

        phonelabel.setText("Phone Number");

        Emaillabel.setText("Email Address");

        Updatebutton.setText("UPDATE");
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Deletebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Viewbutton)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contactlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDlabel)
                                    .addComponent(Agelabel)
                                    .addComponent(Genderlabel)
                                    .addComponent(Startdatelabel)
                                    .addComponent(Levellabel))
                                .addGap(241, 241, 241)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Levelfield)
                                    .addComponent(StartdateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Genderfield)
                                    .addComponent(Agefield)
                                    .addComponent(IDfield)
                                    .addComponent(Namefield)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonelabel)
                            .addComponent(Emaillabel))
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Emailfield)
                            .addComponent(Phonefield))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Updatebutton)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Viewbutton)
                            .addComponent(Deletebutton))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Namelabel)
                            .addComponent(Namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDlabel))
                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agelabel)
                    .addComponent(Agefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genderlabel)
                    .addComponent(Genderfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Startdatelabel)
                    .addComponent(StartdateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Levellabel)
                    .addComponent(Levelfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contactlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonelabel)
                    .addComponent(Phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emaillabel)
                    .addComponent(Emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Updatebutton)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = EmployeeTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete", "Error", HEIGHT);
        } else { 
            DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
            Employee selectedEmployee = (Employee) model.getValueAt(selectedIndex, 0);
            Employees.removeEmployee(selectedEmployee);
            JOptionPane.showMessageDialog(this, "Employee Information is deleted successfully", "Success", HEIGHT);
        populateTable();
        }
        clearFields();
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void ViewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbuttonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = EmployeeTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete", "Error", HEIGHT);
        } else {
            DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
            Employee selectedEmployee = (Employee) model.getValueAt(selectedIndex, 0);
        Namefield.setText(selectedEmployee.getName(Namefield.getText()));
        IDfield.setText(selectedEmployee.getEmployeeID(IDfield.getText()));
        Agefield.setText(selectedEmployee.getAge(Agefield.getText()));
        Genderfield.setText(selectedEmployee.getGender(Genderfield.getText()));
        StartdateChooser.setDateFormatString(String.valueOf(selectedEmployee.getStartDate(StartdateChooser.getDate())));
        Levelfield.setText(selectedEmployee.getLevel(Levelfield.getText()));
        Phonefield.setText(selectedEmployee.getPhoneNumber(Phonefield.getText()));
        Emailfield.setText(selectedEmployee.getEmailAddress(Emailfield.getText()));
            
            
        }
    }//GEN-LAST:event_ViewbuttonActionPerformed

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
        // TODO add your handling code here:
        Employee selectedEmployee;
        int selectedIndex = EmployeeTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete", "Error", HEIGHT);
        } else {
            DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
            selectedEmployee = (Employee) model.getValueAt(selectedIndex, 0);
            selectedEmployee.getName(Namefield.getText());
            selectedEmployee.getEmployeeID(IDfield.getText());
            selectedEmployee.getAge(Agefield.getText());
            selectedEmployee.getGender(Genderfield.getText());
            selectedEmployee.getStartDate(StartdateChooser.getDate());
            selectedEmployee.getLevel(Levelfield.getText());
            selectedEmployee.getPhoneNumber(Phonefield.getText());
            selectedEmployee.getEmailAddress(Emailfield.getText());
            
        
        JOptionPane.showMessageDialog(this, "Employee Details Updated Successfully", "Success", HEIGHT);
    populateTable();
        }                                    
    
        
    }//GEN-LAST:event_UpdatebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agefield;
    private javax.swing.JLabel Agelabel;
    private javax.swing.JLabel Contactlabel;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JTextField Genderfield;
    private javax.swing.JLabel Genderlabel;
    private javax.swing.JTextField IDfield;
    private javax.swing.JLabel IDlabel;
    private javax.swing.JTextField Levelfield;
    private javax.swing.JLabel Levellabel;
    private javax.swing.JTextField Namefield;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JTextField Phonefield;
    private com.toedter.calendar.JDateChooser StartdateChooser;
    private javax.swing.JLabel Startdatelabel;
    private javax.swing.JLabel Titlelabel;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JButton Viewbutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel phonelabel;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
    DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
    model.setRowCount(0);
    for (Employee emp : Employees.getAllEmployees()) {
        Object[] row = new Object[8];
        row[0] = emp;
        row[1] = emp.getEmployeeID(IDfield.getText());
        row[2] = emp.getAge(Agefield.getText());
        row[3] = emp.getGender(Genderfield.getText());
        row[4] = emp.getStartDate(StartdateChooser.getDate());
        row[5] = emp.getLevel(Levelfield.getText());
        row[6] = emp.getPhoneNumber(Phonefield.getText());
        row[7] = emp.getEmailAddress(Emailfield.getText());
        model.addRow(row);
    }
    clearFields();
    }

    public void clearFields() {
        Namefield.setText("");
        IDfield.setText("");
        Agefield.setText("");
        Genderfield.setText("");
        StartdateChooser.setDateFormatString("");
        Levelfield.setText("");
        Phonefield.setText("");
        Emailfield.setText("");
        
        
        
        
    }
}

      
      
      
          
        
              
              
              
     
      
        
        
        
        
